---
- name: get begining of Docker userns-remap sub UID/GID range (custom Docker user)
  block:
    - name: get /etc/subuid entry of Docker user
      shell: |
        set -o pipefail
        cat /etc/subuid | grep {{ docker_userns_remap_user }}
      args:
        executable: /bin/bash
      register: _result
      changed_when: false
    - name: get begining of sub UID range
      set_fact:
        gitlab_docker_userns_remap_subuid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"

    - name: get /etc/subgid entry of Docker user
      shell: |
        set -o pipefail
        cat /etc/subgid | grep {{ docker_userns_remap_user }}
      args:
        executable: /bin/bash
      register: _result
      changed_when: false
    - name: get begining of sub GID range
      set_fact:
        gitlab_docker_userns_remap_subgid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"
  when:
    - docker_userns_remap_user is defined
    - docker_userns_remap_user != 'default'

- name: get begining of Docker userns-remap sub UID/GID range (default Docker user)
  block:
    - name: get /etc/subuid entry of Docker user
      shell: |
        set -o pipefail
        cat /etc/subuid | grep dockremap
      args:
        executable: /bin/bash
      register: _result
      changed_when: false
    - name: get begining of sub UID range
      set_fact:
        gitlab_docker_userns_remap_subuid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"

    - name: get /etc/subgid entry of Docker user
      shell: |
        set -o pipefail
        cat /etc/subgid | grep dockremap
      args:
        executable: /bin/bash
      register: _result
      changed_when: false
    - name: get begining of sub GID range
      set_fact:
        gitlab_docker_userns_remap_subgid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"
  when: docker_userns_remap_user is undefined or docker_userns_remap_user == 'default'
