---
- name: get info about userns-remap sub UID ranges (custom Docker user)
  shell: |
    set -o pipefail
    cat /etc/subuid | grep {{ docker_userns_remap_user }}
  args:
    executable: /bin/bash
  register: _result
  changed_when: false
  when:
    - docker_userns_remap_user is defined
    - docker_userns_remap_user != 'default'

- name: get info about userns-remap sub UID ranges (default Docker user)
  shell: |
    set -o pipefail
    cat /etc/subuid | grep dockremap
  args:
    executable: /bin/bash
  register: _result
  changed_when: false
  when: docker_userns_remap_user is undefined or docker_userns_remap_user == 'default'

- name: get begining of target userns-remap sub UID range
  set_fact:
    gitlab_docker_userns_remap_subuid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"

- name: get info about userns-remap sub GID ranges (custom Docker group)
  shell: |
    set -o pipefail
    cat /etc/subgid | grep {{ docker_userns_remap_user }}
  args:
    executable: /bin/bash
  register: _result
  changed_when: false
  when:
    - docker_userns_remap_user is defined
    - docker_userns_remap_user != 'default'

- name: get info about userns-remap sub GID ranges (default Docker group)
  shell: |
    set -o pipefail
    cat /etc/subgid | grep dockremap
  args:
    executable: /bin/bash
  register: _result
  changed_when: false
  when: docker_userns_remap_user is undefined or docker_userns_remap_user == 'default'

- name: get begining of target userns-remap sub GID range
  set_fact:
    gitlab_docker_userns_remap_subgid_begin: "{{ _result.stdout_lines[0].split(':')[1] }}"
