---
- name: install Docker
  import_role:
    name: yabusygin.docker

- name: create configuration directory
  file:
    path: /etc/docker-gitlab
    state: directory
    mode: 0700

- name: get userns-remap UID/GID ranges
  import_tasks: get-docker-userns-remap-info.yml
  when: docker_userns_remap_enable|default(false)

- name: create config file
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
    lstrip_blocks: yes
    mode: 0600
  when: not docker_userns_remap_enable|default(false)
  notify:
    - restart GitLab

- name: create config file (userns-remap)
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
    lstrip_blocks: yes
    owner: "{{ docker_userns_remap_subuid_begin }}"
    group: "{{ docker_userns_remap_subgid_begin }}"
    mode: 0600
  when: docker_userns_remap_enable|default(false)
  notify:
    - restart GitLab

- name: create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker-gitlab/docker-compose.yml
    lstrip_blocks: yes
  notify:
    - restart GitLab

- name: run GitLab
  docker_compose:
    state: present
    project_src: /etc/docker-gitlab
