---
- name: install Docker
  import_role:
    name: yabusygin.docker

- name: create configuration directory
  file:
    path: /etc/docker-gitlab
    state: directory

- name: create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker-gitlab/docker-compose.yml
