---
- name: install Docker
  import_role:
    name: yabusygin.docker

- name: create configuration directory
  file:
    path: /etc/docker-gitlab
    state: directory

- name: create config file
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
  notify:
    - restart GitLab

- name: create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker-gitlab/docker-compose.yml
  notify:
    - restart GitLab

- name: run GitLab
  docker_compose:
    state: present
    project_src: /etc/docker-gitlab
