---
- name: create configuration directory
  ansible.builtin.file:
    path: /etc/docker-gitlab
    state: directory
    mode: 0755

- name: create container build directory
  ansible.builtin.file:
    path: /etc/docker-gitlab/build
    state: directory
    mode: 0755

- name: set Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: /etc/docker-gitlab/build/Dockerfile
    lstrip_blocks: yes
    mode: 0644

- name: set .dockerignore
  ansible.builtin.copy:
    src: dockerignore
    dest: /etc/docker-gitlab/build/.dockerignore
    mode: 0644

- name: upload HTTPS key
  ansible.builtin.copy:
    src: "{{ gitlab_https_key }}"
    dest: /etc/docker-gitlab/build/https.key
    mode: 0600
  when: gitlab_https_key is defined

- name: upload HTTPS certificate
  ansible.builtin.copy:
    src: "{{ gitlab_https_cert }}"
    dest: /etc/docker-gitlab/build/https.crt
    mode: 0644
  when: gitlab_https_cert is defined

- name: add SMTP CA certificate
  ansible.builtin.copy:
    src: "{{ gitlab_email_smtp_ca_cert }}"
    dest: /etc/docker-gitlab/build/smtp.ca.crt
    mode: 0600
  when: gitlab_email_smtp_ca_cert is defined

- name: create Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /etc/docker-gitlab/docker-compose.yml
    lstrip_blocks: yes
    mode: 0600
  notify:
    - restart GitLab

- name: add backup helper script
  ansible.builtin.copy:
    src: gitlab-backup-wrapper
    dest: /usr/local/bin/gitlab-backup-wrapper
    mode: 0755

- name: configure automated backups
  ansible.builtin.template:
    src: gitlab-backup.cron.j2
    dest: /etc/cron.d/gitlab-backup
    lstrip_blocks: yes
    mode: 0644
  when: gitlab_backup_cron_enable

- name: run GitLab
  community.docker.docker_compose:
    state: present
    project_src: /etc/docker-gitlab
