---
- name: create configuration directory
  file:
    path: /etc/docker-gitlab
    state: directory
    mode: 0755

- name: get userns-remap UID/GID ranges
  import_tasks: get-userns-info.yml
  when: gitlab_userns_enable

- name: create config file
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
    lstrip_blocks: yes
    owner: "{{ _bindmount_owner }}"
    group: "{{ _bindmount_group }}"
    mode: 0600
  notify:
    - restart GitLab

- name: add SMTP CA certificate
  copy:
    src: "{{ gitlab_email_smtp_ca_cert }}"
    dest: /etc/docker-gitlab/smtp-ca.crt
    owner: "{{ _bindmount_owner }}"
    group: "{{ _bindmount_group }}"
    mode: 0600
  when: gitlab_email_smtp_ca_cert is defined
  notify:
    - restart GitLab

- name: create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker-gitlab/docker-compose.yml
    lstrip_blocks: yes
    mode: 0600
  notify:
    - restart GitLab

- name: run GitLab
  docker_compose:
    state: present
    project_src: /etc/docker-gitlab
