---
- name: get subordinate UID range begining of Docker user
  shell: |
    set -o pipefail
    grep {{ gitlab_userns_remap_user }} /etc/subuid | awk -F ':' '{ print $2 }'
  args:
    executable: /bin/bash
  register: _range_begin
  changed_when: false

- name: set owner ID for files that are mounted to container
  set_fact:
    _volume_owner: "{{ _range_begin.stdout|int + _volume_owner }}"

- name: get subordinate GID range begining of Docker user
  shell: |
    set -o pipefail
    grep {{ gitlab_userns_remap_user }} /etc/subgid | awk -F ':' '{ print $2 }'
  args:
    executable: /bin/bash
  register: _range_begin
  changed_when: false

- name: set group ID for files that are mounted to container
  set_fact:
    _volume_group: "{{ _range_begin.stdout|int + _volume_group }}"
