---
- name: get subordinate UID range begining of Docker user
  ansible.builtin.shell: |
    set -o pipefail
    grep {{ gitlab_userns_remap_user }} /etc/subuid | awk -F ':' '{ print $2 }'
  args:
    executable: /bin/bash
  register: _range_begin
  changed_when: false

- name: set owner ID for files that are mounted to container
  ansible.builtin.set_fact:
    _gitlab_volume_owner: "{{ _range_begin.stdout | int + _gitlab_volume_owner }}"

- name: get subordinate GID range begining of Docker user
  ansible.builtin.shell: |
    set -o pipefail
    grep {{ gitlab_userns_remap_user }} /etc/subgid | awk -F ':' '{ print $2 }'
  args:
    executable: /bin/bash
  register: _range_begin
  changed_when: false

- name: set group ID for files that are mounted to container
  ansible.builtin.set_fact:
    _gitlab_volume_group: "{{ _range_begin.stdout | int + _gitlab_volume_group }}"
