---
- name: converge
  hosts: instance
  tasks:
    - name: install Docker
      ansible.builtin.import_role:
        name: yabusygin.docker

    - name: install GitLab
      ansible.builtin.import_role:
        name: yabusygin.gitlab

    - name: install HTTPie
      ansible.builtin.pip:
        name:
          - httpie
        state: present
