---
dependency:
  name: galaxy
driver:
  name: docker
lint: ./lint.sh
platforms:
  - name: instance
    image: ${TEST_IMAGE}
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    keep_volumes: false
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
