---
- name: prepare
  hosts: instance
  gather_facts: false
  tasks:
    - name: install Python 3 for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      become: true
      changed_when: false
