---
- name: converge
  hosts: instance
  tasks:
    - name: install Docker
      import_role:
        name: yabusygin.docker

    - name: install GitLab
      import_role:
        name: gitlab

    - name: install HTTPie
      pip:
        name:
          - httpie<2.0.0
        state: present
