---
version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ce:12.7.6-ce.0
    volumes:
      - type: volume
        source: config
        target: /etc/gitlab
      - type: bind
        source: ./gitlab.rb
        target: /etc/gitlab/gitlab.rb
      - type: volume
        source: data
        target: /var/opt/gitlab
      - type: volume
        source: log
        target: /var/log/gitlab
    networks:
      - bridge
    ports:
      - protocol: tcp
        target: 80
        published: 80
      - protocol: tcp
        target: 22
        published: 22
    restart: always
volumes:
  config:
  data:
  log:
networks:
  bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: gitlab
