---
services:
  gitlab:
    build:
      context: ./build
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # URL
        external_url 'https://gitlab.test'
        registry_external_url 'https://gitlab.test:5050'

        # HTTPS
        letsencrypt['enable'] = true

        # Outgoing emails
        gitlab_rails['gitlab_email_enabled'] = false
    volumes:
      - type: volume
        source: config
        target: /etc/gitlab
      - type: volume
        source: data
        target: /var/opt/gitlab
      - type: volume
        source: log
        target: /var/log/gitlab
    networks:
      - bridge
    ports:
      - protocol: tcp
        target: 443
        published: 443
      - protocol: tcp
        target: 22
        published: 22
      - protocol: tcp
        target: 5050
        published: 5050
volumes:
  config:
  data:
  log:
networks:
  bridge:
    driver: bridge
