---
- name: converge
  hosts: instance
  tasks:
    - name: install Docker
      ansible.builtin.import_role:
        name: yabusygin.docker

    - name: install GitLab
      ansible.builtin.import_role:
        name: yabusygin.gitlab

    - name: add root CA certificate
      ansible.builtin.copy:
        src: root.crt.pem
        dest: /etc/ssl/certs/
        mode: u=rw,g=r,o=r

    - name: install HTTPie
      ansible.builtin.pip:
        name:
          - httpie
        state: present
