---
dependency:
  name: galaxy
driver:
  name: docker
lint: ./lint.sh
platforms:
  - name: instance
    image: ${TEST_IMAGE}
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Required for Docker in Docker. Default storage drivers (aufs/overlay2)
      # don't support AUFS/OverlayFS backing filesystem.
      - /var/lib/docker
    keep_volumes: false
    privileged: true
    pre_build_image: true
    etc_hosts:
      gitlab.test: 127.0.0.1
provisioner:
  name: ansible
verifier:
  name: testinfra
