---
- name: converge gitlab
  hosts: gitlab
  tasks:
    - name: install Docker
      import_role:
        name: yabusygin.docker

    - name: install GitLab
      import_role:
        name: yabusygin.gitlab

    - name: install HTTPie
      pip:
        name:
          - httpie<2.0.0
        state: present

- name: converge smtp
  hosts: smtp
  tasks:
    - name: add mailbox testing util
      copy:
        src: contains_message.py
        dest: /usr/bin/contains_message.py
        mode: 0755
