# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}


{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN apt-get update && \
    apt-get install --yes \
        python3 \
        python3-venv && \
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install 'aiosmtpd>=1.4,<1.5'

ENTRYPOINT ["/venv/bin/aiosmtpd", "--listen=0.0.0.0:25"]

EXPOSE 25
