---
gitlab_rails_smtp_enable: 'true'
gitlab_rails_smtp_address: smtp.example.com
gitlab_rails_smtp_port: 465
gitlab_rails_smtp_user_name: gitlab
gitlab_rails_smtp_password: 'Pa$$w0rD'
gitlab_rails_smtp_domain: example.com
gitlab_rails_smtp_authentication: login
gitlab_rails_smtp_enable_starttls_auto: 'true'
gitlab_rails_smtp_openssl_verify_mode: peer
gitlab_rails_smtp_tls: 'true'
gitlab_rails_smtp_ssl: 'true'
gitlab_rails_smtp_force_ssl: 'true'
gitlab_rails_gitlab_email_enabled: 'true'
gitlab_rails_gitlab_email_from: gitlab@example.com
gitlab_rails_gitlab_email_display_name: GitLab
gitlab_rails_gitlab_email_reply_to: noreply@example.com
