---
version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ce:12.7.6-ce.0
    hostname: gitlab
    volumes:
      - type: volume
        source: config
        target: /etc/gitlab
      - type: bind
        source: ./gitlab.rb
        target: /etc/gitlab/gitlab.rb
      - type: bind
        source: ./smtp-ca.crt
        target: /etc/gitlab/ssl/smtp-ca.crt
      - type: volume
        source: data
        target: /var/opt/gitlab
      - type: volume
        source: log
        target: /var/log/gitlab
    networks:
      - bridge
    ports:
      - protocol: tcp
        target: 8000
        published: 8000
      - protocol: tcp
        target: 22
        published: 2222
      - protocol: tcp
        target: 5001
        published: 5001
    restart: always
volumes:
  config:
  data:
  log:
networks:
  bridge:
    driver: bridge
