#!/bin/sh

set -o errexit

project_path=/etc/docker-gitlab
service_name=gitlab

print_error() {
    echo "error:" "$@" >&2
}

container_id=$(
    docker-compose --project-directory="${project_path}" \
        ps --quiet ${service_name}
)
if [ -z ${container_id} ]; then
    print_error "GitLab container is stopped"
    exit 1
fi

container_id=$(
    docker ps \
        --quiet \
        --filter="id=${container_id}" \
        --filter="status=running" \
        --filter="health=healthy"
)
if [ -z ${container_id} ]; then
    print_error "GitLab container is not up and healthy"
    exit 1
fi

docker exec ${container_id} \
    /opt/gitlab/bin/gitlab-backup create CRON=1
