---
- name: converge gitlab
  hosts: gitlab
  tasks:
    - name: install Docker
      ansible.builtin.import_role:
        name: yabusygin.docker

    - name: install GitLab
      ansible.builtin.import_role:
        name: yabusygin.gitlab

    - name: install ansible.builtin.pip module dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: install amazon.aws.aws_s3 module dependencies
      ansible.builtin.pip:
        name:
          - boto3
        state: present

    - name: create bucket for backups
      amazon.aws.aws_s3:
        rgw: yes
        s3_url: "{{ gitlab_backup_upload_s3_endpoint }}"
        bucket: "{{ gitlab_backup_upload_s3_bucket }}"
        aws_access_key: "{{ gitlab_backup_upload_s3_access_key_id }}"
        aws_secret_key: "{{ gitlab_backup_upload_s3_secret_access_key }}"
        mode: create
