---
- name: converge gitlab
  hosts: gitlab
  tasks:
    - name: install Docker
      import_role:
        name: yabusygin.docker

    - name: install GitLab
      import_role:
        name: yabusygin.gitlab

- name: converge S3 mock
  hosts: s3
  tasks:
    - name: install Python
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: install amazon.aws.aws_s3 module dependencies
      pip:
        name:
          - boto3
        state: present

    - name: create bucket for backups
      amazon.aws.aws_s3:
        s3_url: http://s3.test
        region: us-east-1
        bucket: gitlab-backup
        aws_access_key: local-identity
        aws_secret_key: local-credential
        mode: create
        rgw: yes
