---
dependency:
  name: galaxy
driver:
  name: docker
lint: ./lint.sh
platforms:
  - name: gitlab
    image: ${TEST_IMAGE}
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    keep_volumes: false
    privileged: true
    networks_cli_compatible: yes
    networks:
      - name: test-s3
        aliases:
          - gitlab.test
  - name: s3
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z
    pre_build_image: true
    command:
      - server
      - /data
    env:
      MINIO_BROWSER: "off"
    volumes:
      - /data
    keep_volumes: false
    networks_cli_compatible: yes
    networks:
      - name: test-s3
        aliases:
          - s3.test
provisioner:
  name: ansible
verifier:
  name: ansible
