---
name: release
on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: release to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: install dependencies
        run: python -m pip install ansible
      - name: import role to Ansible Galaxy
        run: ansible-galaxy role import --api-key $GALAXY_API_KEY $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
        env:
          GALAXY_API_KEY: ${{ secrets.galaxy_api_key }}
