---
name: test
on:
  push:
    branches:
      - "**"
jobs:
  templtest:
    name: test templates
    runs-on: ubuntu-latest
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.0.2

      - name: set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: install requirements
        run: python -m pip install --requirement "$GITHUB_WORKSPACE/gitlab/requirements.txt"

      - name: test templates
        run: |
          cd $GITHUB_WORKSPACE/gitlab
          templtest

  molecule:
    name: run Molecule tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "geerlingguy/docker-debian10-ansible:latest"
          - "geerlingguy/docker-ubuntu1804-ansible:latest"
          - "geerlingguy/docker-ubuntu2004-ansible:latest"
        scenario:
          - default
          - userns_remap
          - https
          - smtp
          - s3_backup
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.0.2

      - name: set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: install requirements
        run: python -m pip install --requirement "$GITHUB_WORKSPACE/gitlab/requirements.txt"

      - name: run Molecule tests
        run: |
          cd $GITHUB_WORKSPACE/gitlab
          molecule test --scenario-name $TEST_SCENARIO
        env:
          TEST_IMAGE: ${{ matrix.image }}
          TEST_SCENARIO: ${{ matrix.scenario }}
