---
name: test
on:
  push:
    branches:
      - "**"
jobs:
  templtest:
    name: test templates
    runs-on: ubuntu-latest
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.0.2

      - name: set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: install requirements
        run: python -m pip install --requirement=requirements.txt

      - name: test templates
        run: templtest

  molecule:
    name: run Molecule tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "geerlingguy/docker-debian10-ansible:latest"
          - "geerlingguy/docker-debian11-ansible:latest"
          - "geerlingguy/docker-ubuntu2004-ansible:latest"
          - "geerlingguy/docker-ubuntu2204-ansible:latest"
        scenario:
          - default
          - https
          - smtp
          - s3_backup
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.0.2

      - name: set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: install requirements
        run: python -m pip install --requirement=requirements.txt

      - name: run Molecule tests
        run: molecule test --scenario-name=${TEST_SCENARIO}
        env:
          TEST_IMAGE: ${{ matrix.image }}
          TEST_SCENARIO: ${{ matrix.scenario }}
