---
name: test
on:
  - push
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "geerlingguy/docker-debian9-ansible:latest"
          - "geerlingguy/docker-debian10-ansible:latest"
          - "geerlingguy/docker-ubuntu1804-ansible:latest"
          - "geerlingguy/docker-ubuntu2004-ansible:latest"
        scenario:
          - default
          - userns_remap
          - https
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          path: gitlab
      - name: set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: install dependencies
        run: python -m pip install --requirement "$GITHUB_WORKSPACE/gitlab/requirements.txt"
      - name: run templates rendering tests
        run: |
          cd $GITHUB_WORKSPACE/gitlab
          templtest
      - name: run molecule tests
        run: |
          cd $GITHUB_WORKSPACE/gitlab
          molecule test --scenario-name $TEST_SCENARIO
        env:
          TEST_IMAGE: ${{ matrix.image }}
          TEST_SCENARIO: ${{ matrix.scenario }}
